---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: centos-7.2
    driver_config:
      provision_command:
        - yum -y install iproute
        - yum -y install net-tools
      image: ansible/centos7-ansible:stable
      platform: centos

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: false

verifier:
  name: serverspec

suites:
  - name: default
    verifier:
      patterns:
        - roles/demo/test/integration/default/serverspec/default_spec.rb
